### PR TITLE
- Remove usage of jQuery in pgAdmin.

### PR DESCRIPTION
**Pull request by adityatoshniwal**
- Remove usage of Bootstrap in React components. #5701

### CODE REVIEW

**Comment by adityatoshniwal** [comment]
Impacted areas:

**Comment by adityatoshniwal** [comment]
Impacted areas:
**Please note, all to be tested for both success and error scenarios**
**Jquery Impact**

- Table/Partition -> Compound trigger, trigger, rule - Enable, Disable, 
- Table -> Check Constraint, FK - Validate,
- Table/Partition -> Truncate, Reset statistics, Detach partition
- Mview -> Refresh
- Server, Database -> Connect, Disconnect
- Server -> Reload config, Change Password, WAL replay, Clear saved password, Clear SSH tunnel pass, Refresh server, Bg and Fg color change.
- pgAgent Job -> Run
- Master password - set, reset.
- Lock layout.
- Delete a node.
- Realtime Preference Change.
- Reset Layout.
- Tree state save.

**Bootstrap UI**

- About
- Panels - Dashboard, Properties, Deps, etc,
- Quick search
- Grant Wizard
- Open all the tools

**Comment by adityatoshniwal** [comment]
Please postpone this PR until next release.

**Comment by yogeshmahajan-1903** [comment]
Here are some issues found in initial testing - 
1.Schmea diff UI is broken
2.ERD tool -
 1.Unable to move tables when ERD is drawn for database. 
 2.Zoom to fit button sets ERD in center, after that unable to move to right side.
 3.Once table is selected, can not be unselected.
 
3.Server BG/FG color not getting applied.

**Pull request merged**
