### PR TITLE
Fixed issues reported in #7958

### PR DESCRIPTION
**Pull request by asheshv**
- Search wasn't working as we were using wrong row-index, while rendering it.
- Fixed the CSS issue with the alignment of the search input box.
- Pass the row object while rendering the 'DataRow' component, to improve the performance as it was calling the filtering function repeatedly for each row.
- Changed the order of the validators on a field to priortize the 'empty' string validator over the unique-id validator in a collection.

### CODE REVIEW

**Comment by anilsahoo20** [comment]
The search box result is wrong.

Expected search box width
Screenshot 2024-09-23 at 3 46 49 PM

Current search box width
Screenshot 2024-09-23 at 3 46 36 PM

**Comment by asheshv** [comment]
> The search box result is wrong.
> 
> Expected search box width Screenshot 2024-09-23 at 3 46 49 PM
> 
> Current search box width Screenshot 2024-09-23 at 3 46 36 PM

It is not a side effect or bug, but - It has been changed like that intentionally.

**Comment by anilsahoo20** [comment]
The partition tab in edit dialog of table is not showing.
Screenshot 2024-09-23 at 4 07 51 PM

**Comment by anilsahoo20** [comment]
The search box result is correctly displayed.

One remaining issue still not fixed i.e. `Note is missing in Existing table>Edit dialog>Partitions tab.`

**Pull request merged**
