### PR TITLE
python 3 updates

### PR DESCRIPTION
**Pull request by marksmayo**
- fix super() calls for python 3
- no need to inherit object
- no need for u at start of strings
- tidied up some brackets and f-strings too

### CODE REVIEW

**Comment by akshay-joshi** [comment]
@marksmayo Please fix the PEP8 issues.

**Comment by adityatoshniwal** [comment]
@marksmayo Great work there ! Did you use any tool or lib to find these ?

**Review by adityatoshniwal — APPROVED** [review]
The changes looks good to me, except the PEP8 failure.

**Comment by marksmayo** [comment]
@adityatoshniwal pylint_runner mainly (it executes pylint across a codebase).  Then ignore some of the 'sillier' warnings and focus on python 3 ones.

**Comment by marksmayo** [comment]
@akshay-joshi believe they're fixed, just need it checked again via workflows

**Pull request merged**
