### PR TITLE
feat: Preview Environments for every PR using Uffizzi

### PR DESCRIPTION
**Pull request by ShrutiC-git**
Hi, this is a PR addressing https://github.com/pgadmin-org/pgadmin4/issues/5441

### What does this PR do?
This PR is adding support for **preview environments for every PR opened against pgAdmin** using [Uffizzi ](https://uffizzi.com/). The PR is extending pgAdmin's GHA workflows to **create ephemeral preview environments so each PR and its impact can be tested easily and quickly 🚀**. The URL of the preview environment is posted as a comment on the PR for easy access. 

### Testing 
A demo of how these Preview Environments work:

[This is a PR on my personal fork of pgadmin](https://github.com/ShrutiC-git/pgadmin4/pull/1) from a feature branch to the main branch. A new [comment](https://github.com/ShrutiC-git/pgadmin4/pull/1#issuecomment-1307195054) was posted on the PR which lists the [preview-environment-URL](https://app.uffizzi.com//github.com/ShrutiC-git/pgadmin4/pull/1) where the pgAdmin, with code changes from the PR, can be viewed. 

When you visit this URL, you will see the pgAdmin's login screen. Use the following credentials to login: 
`username: admin@admin.com
password: secret
` 

This PR also has an instance of Postgres, named _root_, running on _localhost_ attached to pgAdmin to allow admins to have a holistic look at these preview environments.

cc @waveywaves

### CODE REVIEW

**Comment by adityatoshniwal** [comment]
@ShrutiC-git Nice work there !
But are you sure `username: admin password: admin` will work? pgAdmin allows email Id only as username if using pgAdmin internal authentication.

**Comment by ShrutiC-git** [comment]
oh, thanks for the check, @adityatoshniwal! Accidentally put Postgres credentials
 - updated the credentials for pgAdmin login screen :)🙏🏼

**Comment by ShrutiC-git** [comment]
Hi, @dpage! 
Looping you in on this PR - my colleague was discussing this issue with you. 
What do you think about the PR and about the prospect of having preview environments provisioned by Uffizzi for PRs on pgAdmin? Any feedback and suggestion would be of immense value!

**Comment by dpage** [comment]
Unfortunately the T&Cs for use of Uffizzi are not acceptable to the project due to trademark and liability concerns. Therefore I'm closing this PR.

**Pull request closed without merging**
